# Generated by Django 4.1.5 on 2023-01-31 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\t)'), (' ', 'Space ( )'), ('|', 'Vertical bar (|)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('processing', ' Processing '), ('ready', ' Ready '), ('error', 'Error ')], default='processing', max_length=15)),
                ('rows', models.PositiveIntegerField()),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_data', to='csv_generator.dataschema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(max_length=15)),
                ('data_type', models.CharField(choices=[('Full name', 'Full name'), ('Name', 'Name'), ('Last Name', 'Last Name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date'), ('Age', 'Age')], max_length=15)),
                ('order', models.PositiveIntegerField()),
                ('data_range_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='from')),
                ('data_range_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='to')),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_generator.dataschema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
