name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.13, ]

    steps:
    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: |
            /opt/hostedtoolcache/Python/3.9.13/x64/  # Change to match your Python version
            cache/pip
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements/dev.txt') }}
        restore-keys: |
            ${{ runner.os }}-venv-

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/develop.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: 'config.settings.test'
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        TEST: 11
      run: |
        python3 manage.py test
    - name: Job Status
      run: echo "🍏 Testing status is ${{ job.status }}."
